#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

#resolution
if xrandr | grep "DP1 disconnected"
then
        xrandr --output eDP1 --mode 1920x1080
else
        xrandr --output DP1 --mode 2560x1080 --output eDP1 --off
fi

# key bindings
pkill sxhkd
sxhkd&

# panel
pkill polybar
polybar default&

# Set some bsp specific stuff
if xrandr | grep "DP1 disconnected"
then
        bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else
        bspc monitor DP1 -d I II III IV V VI VII VIII IX X
fi


bspc config window_gap 5
bspc config border_width 3

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#visual options
bspc config normal_border_color "#1c2023"
bspc config active_border_color "#1c2023"
bspc config focused_border_color "#8fa1b3"

#rules
bspc rule -a Zathura state=tiled
bspc rule -a Emacs  state=tiled

#wallpaper
nitrogen --restore

#autostart
owncloud&
blueberry-tray&
